# kompilator c
CCOMP = gcc

# konsolidator
LOADER = gcc

# opcje optymalizacji:
# wersja do debugowania
#OPT = -g -DDEBUG
# wersja zoptymalizowana do mierzenia czasu
OPT = -O3

# pliki naglowkowe
INC = -I../pomiar_czasu

# biblioteki
LIB = -L../pomiar_czasu -l pomiar_czasu -lm

# zaleznosci i komendy
moj_program: moj_program.o 
	$(LOADER) $(OPT) moj_program.o -o moj_program $(LIB)

# jak uzyskac plik moj_program.o ?
moj_program.o: moj_program.c ../pomiar_czasu/pomiar_czasu.h
	$(CCOMP) -c $(OPT) moj_program.c $(INC)


# pomiar_czasu.o: pomiar_czasu.c pomiar_czasu.h
# 	$(CCOMP) -c $(OPT) pomiar_czasu.c 

clean:
	rm -f *.o
